--values(ANALISTA_ID, NOMBRE, APELLIDO)
INSERT INTO ANALISTA_SISMOS VALUES(1, "Lionel", "Messi");
INSERT INTO ANALISTA_SISMOS VALUES(2, "Franco", "Colapinto");
INSERT INTO ANALISTA_SISMOS VALUES(3, "Ricardo", "Fort");

--VALUES(ALCANCE_SISMO_ID, DESCRIPCION, NOMBRE)
INSERT INTO ALCANCE_SISMO VALUES(1, "ALCANCE MEDIANO", "MEDIO" );
INSERT INTO ALCANCE_SISMO VALUES(2, "ALCANCE LARGO", "LARGO" );
INSERT INTO ALCANCE_SISMO VALUES(3, "ALCANCE EXTENSO", "EXTENSO" );
INSERT INTO ALCANCE_SISMO VALUES(4, "ALCANCE CORTO", "CORTO" );
INSERT INTO ALCANCE_SISMO VALUES(5, "ALCANCE MUY CORTO", "MUY CORTO" );

--VALUES(CLASIFICACION_ID, KM_PROFUNDIDAD_HASTA, KM_PROFUNDIDAD_DESDE, NOMBRE)
INSERT INTO CLASIFICACION_SISMO VALUES (1, 10, 5, "MEDIA");
INSERT INTO CLASIFICACION_SISMO VALUES (1, 50, 10, "FUERTE");
INSERT INTO CLASIFICACION_SISMO VALUES (1, 5, 0, "BAJO");

--VALUES(ESTADO_ID, NOMBRE)
INSERT INTO ESTADO VALUES(1, "AUTO_CONFIRMADO");
INSERT INTO ESTADO VALUES(2, "AUTO_DETECTADO");
INSERT INTO ESTADO VALUES(3, "BLOQUEADO");
INSERT INTO ESTADO VALUES(4, "CERRADO");
INSERT INTO ESTADO VALUES(5, "CONFIRMADO");
INSERT INTO ESTADO VALUES(6, "DERIVADO");
INSERT INTO ESTADO VALUES(7, "EVENTO_SIN_REVISION");
INSERT INTO ESTADO VALUES(8, "PENDIENTE_DE_CIERRE");
INSERT INTO ESTADO VALUES(9, "PENDIENTE_DE_REVISION");
INSERT INTO ESTADO VALUES(10, "RECHAZADO");

--VALUES(ESTACION_SISMOLOGICA_ID, CODIGO_ESTACION, DOCUMENTO_CERFICICACION_NUM, FECHA_SOLICITUD_CERTIFICACION, LATITUD, LONGITUD, NOMBRE, NUM_CERTIFICACION)
INSERT INTO ESTACION_SISMOLOGICA VALUES(1, 100, 1, "2025-09-06 17:01:15", 11.23, 12.3, "ESTACION1", 500);

--VALUES(MAGINTUD_RITCHER_ID, DESCRIPCION, NUMERO)
INSERT INTO MAGINTUD_RITCHER VALUES(1, "MAGNITUD DE RITCHER", 7);

--VALUES(ORIGEN_GENERACION_ID, DESCRIPCION, NOMBRE)
INSERT INTO ORIGEN_GENERACION VALUES (1, "ORIGEN NATURAL DE LOS SISMOS", "NATURAL");

--VALUES(TIPO_DATO_ID, DENOMINACION, UNIDAD_MEDIDA, VALOR_UMBRAL)
INSERT INTO TIPO_DATO VALUES (1, "METROS SEGUNDO","M/S", 333333333);

--VALUES(USUARIO_ID, CONTRASENA, ANALISTA_ID, NOMBRE)
INSERT INTO USUARIO VALUES(1, "SALCHICHA", 1, "SALCHICHON");

--VALUES(SISMOGRAFO_ID, FECHA_ADQUISICION, NUMERO_SERIE, ESTACION_SISMOLOGICA_ID)
INSERT INTO SISMOGRAFO VALUES(1, "2025-09-06 17:01:15", 111999, 1);

--VALUES(SESION_ID, USUARIO_ID, FECHA_INICIO, FECHA_FIN)
INSERT INTO SESION VALUES(1, 1, "2025-10-07 18:00:50", "2025-10-07 18:55:53");

--VALUES(EVENTO_ID, FECHA_EVENTO, LATITUD_EPICENTRO, LATITUD_HIPOCENTRO, LONGITUD_EPICENTRO, LONGITUD_HIPOCENTRO, VALOR_MAGNITUD, CLASIFICACION_SISMO_ID, MAGNITUD_RITCHER_ID, ALCANCE_SISMO_ID, ORIGEN_GENERACION_ID,ESTADO_ID )
INSERT INTO EVENTO_SISMICO VALUES(1, "2025-10-09 19:05:40", 11.3, 23.3, 12.3, 21.3, 7.4, 1, 1, 1, 1, 9);

--VALUES(CONDICION_ALARMA, FECHA_HORA_INICIO_REGISTRO_MUESTRAS, FECHA_HORA_REGISTRO, FRECUENCIA_MUESTREO, SISMOGRAFO_ID, SERIE_TEMPORAL_ID, EVENTO_ID)
INSERT INTO SERIE_TEMPORAL VALUES("ALARMA", "2025-10-08 15:23:03","2025-10-08 16:00:02", 122.12, 1, 1, 1);

--VALUES(MUESTRA_SISMICA_ID, FECHA_HORA_MUESTRA, SERIE_TEMPORAL_ID)
INSERT INTO MUESTRA_SISMICA VALUES(1, "2025-10-08 15:23:03", 1);

--VALUES(DETALLE_MUESTRA_SISMICA_ID, VALOR_MUESTRA, MUESTRA_SISMICA_ID, TIPO_DATO_ID)
INSERT INTO DETALLE_MUESTRA_SISMICA VALUES(1, 6.3, 1, 1);

--VALUES(CAMBIO_ESTADO_ID, FECHA_HORA_INICIO, FECHA_HORA_FIN, EVENTO_SISMICO_ID, ESTADO_ID, ANALISTA_ID)
INSERT INTO CAMBIO_ESTADO VALUES(1, "2025-10-09 19:05:40", "2025-10-09 19:30:55", 1, 2, 1);