-- schema_ppai.sql
-- Estructura de tablas para PPAI_DATABASE.db

CREATE TABLE "ALCANCE_SISMO" (
    "ALCANCE_SISMO_ID" INTEGER NOT NULL UNIQUE,
    "DESCRIPCION" TEXT,
    "NOMBRE" TEXT,
    PRIMARY KEY("ALCANCE_SISMO_ID" AUTOINCREMENT)
);

CREATE TABLE "ANALISTA_SISMOS" (
    "ANALISTA_ID" INTEGER NOT NULL UNIQUE,
    "NOMBRE" TEXT,
    "APELLIDO" TEXT,
    PRIMARY KEY("ANALISTA_ID" AUTOINCREMENT)
);

CREATE TABLE "ESTADO" (
    "ESTADO_ID" INTEGER NOT NULL UNIQUE,
    "NOMBRE" TEXT NOT NULL,
    PRIMARY KEY("ESTADO_ID" AUTOINCREMENT)
);

CREATE TABLE "CLASIFICACION_SISMO" (
    "CLASIFICACION_SISMO_ID" INTEGER NOT NULL UNIQUE,
    "KM_PROFUNDIDAD_HASTA" INTEGER,
    "KM_PROFUNDIDAD_DESDE" INTEGER,
    "NOMBRE" TEXT,
    PRIMARY KEY("CLASIFICACION_SISMO_ID" AUTOINCREMENT)
);

CREATE TABLE "ORIGEN_GENERACION" (
    "ORIGEN_GENERACION_ID" INTEGER NOT NULL UNIQUE,
    "DESCRIPCION" TEXT,
    "NOMBRE" TEXT,
    PRIMARY KEY("ORIGEN_GENERACION_ID" AUTOINCREMENT)
);

CREATE TABLE "MAGINTUD_RITCHER" (
    "MAGNITUD_RITCHER_ID" INTEGER NOT NULL UNIQUE,
    "DESCRIPCION_MAGNITUD" TEXT,
    "NUMERO" INTEGER,
    PRIMARY KEY("MAGNITUD_RITCHER_ID" AUTOINCREMENT)
);

CREATE TABLE "ESTACION_SISMOLOGICA" (
    "ESTACION_SISMOLOGICA_ID" INTEGER,
    "CODIGO_ESTACION" INTEGER,
    "DOCUMENTO_CERTIFICACION_ADQUISICION" INTEGER,
    "FECHA_SOLICITUD_CERTIFICACION" TEXT,
    "LATITUD" NUMERIC,
    "LONGITUD" NUMERIC,
    "NOMBRE" TEXT,
    "NUMERO_CERTIFICACION_ADQUISICION" INTEGER,
    PRIMARY KEY("ESTACION_SISMOLOGICA_ID")
);

CREATE TABLE "SISMOGRAFO" (
    "SISMOGRAFO_ID" INTEGER NOT NULL UNIQUE,
    "FECHA_ADQUISICION" TEXT,
    "NUMERO_SERIE" INTEGER,
    "ESTACION_SISMOLOGICA_ID" INTEGER,
    PRIMARY KEY("SISMOGRAFO_ID" AUTOINCREMENT),
    FOREIGN KEY("ESTACION_SISMOLOGICA_ID") REFERENCES "ESTACION_SISMOLOGICA"("ESTACION_SISMOLOGICA_ID")
);

CREATE TABLE "EVENTO_SISMICO" (
    "EVENTO_SISMICO_ID" INTEGER NOT NULL UNIQUE,
    "FECHA_HORA_OCURRENCIA" TEXT,
    "LATITUD_EPICENTRO" NUMERIC,
    "LATITUD_HIPOCENTRO" NUMERIC,
    "LONGITUD_EPICENTRO" NUMERIC,
    "LONGITUD_HIPOCENTRO" NUMERIC,
    "VALOR_MAGNITUD" NUMERIC,
    "CLASIFICACION_SISMO_ID" INTEGER,
    "MAGNITUD_RITCHER_ID" INTEGER,
    "ALCANCE_SISMO_ID" INTEGER,
    "ORIGEN_GENERACION_ID" INTEGER,
    "ESTADO_ID" INTEGER NOT NULL,
    PRIMARY KEY("EVENTO_SISMICO_ID" AUTOINCREMENT),
    FOREIGN KEY("ALCANCE_SISMO_ID") REFERENCES "ALCANCE_SISMO"("ALCANCE_SISMO_ID"),
    FOREIGN KEY("CLASIFICACION_SISMO_ID") REFERENCES "CLASIFICACION_SISMO"("CLASIFICACION_SISMO_ID"),
    FOREIGN KEY("ESTADO_ID") REFERENCES "ESTADO"("ESTADO_ID"),
    FOREIGN KEY("MAGNITUD_RITCHER_ID") REFERENCES "MAGINTUD_RITCHER"("MAGNITUD_RITCHER_ID"),
    FOREIGN KEY("ORIGEN_GENERACION_ID") REFERENCES "ORIGEN_GENERACION"("ORIGEN_GENERACION_ID")
);

CREATE TABLE "SERIE_TEMPORAL" (
    "CONDICION_ALARMA" TEXT,
    "FECHA_HORA_INICIO_REGISTRO_MUESTRAS" TEXT,
    "FECHA_HORA_REGISTRO" TEXT,
    "FRECUENCIA_MUESTREO" NUMERIC,
    "SISMOGRAFO_ID" INTEGER NOT NULL,
    "SERIE_TEMPORAL_ID" INTEGER NOT NULL UNIQUE,
    "EVENTO_SISMICO_ID" INTEGER NOT NULL,
    PRIMARY KEY("SERIE_TEMPORAL_ID" AUTOINCREMENT),
    FOREIGN KEY("EVENTO_SISMICO_ID") REFERENCES "EVENTO_SISMICO"("EVENTO_SISMICO_ID"),
    FOREIGN KEY("SISMOGRAFO_ID") REFERENCES "SISMOGRAFO"("SISMOGRAFO_ID")
);

CREATE TABLE "MUESTRA_SISMICA" (
    "MUESTRA_SISMICA_ID" INTEGER NOT NULL UNIQUE,
    "FECHA_HORA_MUESTRA" TEXT,
    "SERIE_TEMPORAL_ID" INTEGER NOT NULL,
    PRIMARY KEY("MUESTRA_SISMICA_ID" AUTOINCREMENT),
    FOREIGN KEY("SERIE_TEMPORAL_ID") REFERENCES "SERIE_TEMPORAL"("SERIE_TEMPORAL_ID")
);

CREATE TABLE "TIPO_DATO" (
    "TIPO_DATO_ID" INTEGER NOT NULL UNIQUE,
    "DENOMINACION" TEXT,
    "UNIDAD_MEDIDA" TEXT,
    "VALOR_UMBRAL" NUMERIC,
    PRIMARY KEY("TIPO_DATO_ID" AUTOINCREMENT)
);

CREATE TABLE "DETALLE_MUESTRA_SISMICA" (
    "DETALLE_MUESTRA_SISMICA_ID" INTEGER NOT NULL UNIQUE,
    "VALOR" NUMERIC,
    "MUESTRA_SISMICA_ID" INTEGER NOT NULL,
    "TIPO_DATO_ID" INTEGER NOT NULL,
    PRIMARY KEY("DETALLE_MUESTRA_SISMICA_ID" AUTOINCREMENT),
    FOREIGN KEY("MUESTRA_SISMICA_ID") REFERENCES "MUESTRA_SISMICA"("MUESTRA_SISMICA_ID"),
    FOREIGN KEY("TIPO_DATO_ID") REFERENCES "TIPO_DATO"("TIPO_DATO_ID")
);

CREATE TABLE "USUARIO" (
    "USUARIO_ID" INTEGER NOT NULL UNIQUE,
    "CONTRASENA" TEXT,
    "ANALISTA_ID" INTEGER,
    "NOMBRE" TEXT,
    PRIMARY KEY("USUARIO_ID" AUTOINCREMENT),
    FOREIGN KEY("ANALISTA_ID") REFERENCES "ANALISTA_SISMOS"("ANALISTA_ID")
);

CREATE TABLE "SESION" (
    "SESION_ID" INTEGER NOT NULL UNIQUE,
    "USUARIO_ID" INTEGER,
    "FECHA_HORA_INICIO" TEXT,
    "FECHA_HORA_FIN" TEXT,
    PRIMARY KEY("SESION_ID" AUTOINCREMENT),
    FOREIGN KEY("USUARIO_ID") REFERENCES "USUARIO"("USUARIO_ID")
);

CREATE TABLE "CAMBIO_ESTADO" (
    "CAMBIO_ESTADO_ID" INTEGER NOT NULL UNIQUE,
    "FECHA_HORA_INICIO" TEXT,
    "FECHA_HORA_FIN" TEXT,
    "EVENTO_SISMICO_ID" INTEGER NOT NULL,
    "ESTADO_ID" INTEGER NOT NULL,
    "ANALISTA_ID" INTEGER NOT NULL,
    PRIMARY KEY("CAMBIO_ESTADO_ID" AUTOINCREMENT),
    FOREIGN KEY("ANALISTA_ID") REFERENCES "ANALISTA_SISMOS"("ANALISTA_ID"),
    FOREIGN KEY("ESTADO_ID") REFERENCES "ESTADO"("ESTADO_ID"),
    FOREIGN KEY("EVENTO_SISMICO_ID") REFERENCES "EVENTO_SISMICO"("EVENTO_SISMICO_ID")
);
